on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
    - uses: actions/checkout@master
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.ACR_CREDENTIALS }}
    - uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "kv-ebuna-acr-secrets"
        secrets: 'acrUsername, acrPassword, acrHost'
      id: myGetSecretAction
    - uses: Azure/docker-login@v1
      with:
        registry: ${{ steps.myGetSecretAction.outputs.acrHost }}
        login-server: ${{ steps.myGetSecretAction.outputs.acrHost }}
        username: ${{ steps.myGetSecretAction.outputs.acrUsername }}
        password: ${{ steps.myGetSecretAction.outputs.acrPassword }}
    - run: |
        trimmedSha=$(echo ${{ github.sha }} | cut -c1-7)
        branchName=$(echo ${GITHUB_REF#refs/heads/})
        docker build . -t ${{ steps.myGetSecretAction.outputs.acrHost }}/shutthedoor:$branchName-$trimmedSha
        docker push ${{ steps.myGetSecretAction.outputs.acrHost }}/shutthedoor:$branchName-$trimmedSha
